// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/cd4debea25a280da0808d4ff2ca5a4bdb34bd28b/domurl/index.d.ts
declare module "domurl" {
    declare class QueryString {
        constructor(qs?: string);
        toString: () => string;
    }

    declare class Url {
        constructor(url?: string);
        query: T;
        protocol: string;
        user: string;
        pass: string;
        host: string;
        port: string;
        path: string;
        hash: string;
        href: string;
        toString: () => string;
        encode: (s: string) => string;
        decode: (s: string) => string;
        isAbsolute: () => boolean;
        paths: (paths?: [string]) => [string];
        isEmptyQuery: () => boolean;
        queryLength: () => number;
        clearQuery: () => Url;
    }

    export = Url;
}